
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  web:
    build:
      context: .
      dockerfile: StackOverflow.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080
    depends_on:
      - mongo
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
